name: CLASHDASH Android Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Unity Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildMethod: Zetra.ClashDash.EditorTools.ArenaOneBuilder.BuildForCI
          androidExportType: androidPackage
          androidKeystoreName: user
          androidAppBundle: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CLASHDASH-Android
          path: build/**/*.apk
